version: '3.8'
services:
  php:
    container_name: phpLab3
    build:
      dockerfile: ./Docker/php/Dockerfile
    volumes:
      - './:/var/www/'
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - './:/var/www/'
      - './Docker/nginx/conf.d:/etc/nginx/conf.d'
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "laravel"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "123123"
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

